### PR TITLE
Add Common GITHUB Items

### PR DESCRIPTION
**Pull request by seahawks8**
Hey John,

I saw a couple of posts in g-groups around labels and templates, figured I would add some of them.
These are the first pass, however, they should be fine moving forward.

- GITHUB PR Templates
- GITHUB ISSUE Templates - I used the tags/issues you posted in g-groups "labels and templates"
- GITHUB Codeowners

The next item I want to do is
- implement linting checks for CI VIA github actions, clippy as a first pass

### CODE REVIEW

**Comment by jfbourdon** [comment]
Nice! I'm happy to learn that it's pretty simple to setup issue templates.

I'm obviously not the codeowner, but I wouldn't add so many templates as I think that too much choice will not help the user in the end. I would really only let _bug_ and _feature_request_ as templates as the other labels will probably be better chosen by a maintainer than a user (speeking here about _feedback_, _unix_, _regression_, _windows_, _wont fix_, _wbt api_, _wbt runner_).

As for _question_, _qgis_plugin_, _arcgis_plugin_ and (potentially _r_package_) I think those templates should not allow to open an issue but instead redirect to the appropriate website (via the config.yml file):

- QGIS plugin: https://github.com/alexbruy/processing-wbt
- ArcGIS plugin: https://github.com/giswqs/WhiteboxTools-ArcGIS
- R package: https://github.com/giswqs/whiteboxR
- Question: https://gis.stackexchange.com/

**Comment by jblindsay** [comment]
I think Jean-Francois has very good points here. Can I ask that you revise this PR in light of these comments and resubmit? That would be appreciated.

**Comment by seahawks8** [comment]
> Nice! I'm happy to learn that it's pretty simple to setup issue templates.
> 
> I'm obviously not the codeowner, but I wouldn't add so many templates as I think that too much choice will not help the user in the end. I would really only let _bug_ and _feature_request_ as templates as the other labels will probably be better chosen by a maintainer than a user (speeking here about _feedback_, _unix_, _regression_, _windows_, _wont fix_, _wbt api_, _wbt runner_).
> 
> As for _question_, _qgis_plugin_, _arcgis_plugin_ and (potentially _r_package_) I think those templates should not allow to open an issue but instead redirect to the appropriate website (via the config.yml file):
> 
> * QGIS plugin: https://github.com/alexbruy/processing-wbt
> * ArcGIS plugin: https://github.com/giswqs/WhiteboxTools-ArcGIS
> * R package: https://github.com/giswqs/whiteboxR
> * Question: https://gis.stackexchange.com/

I removed the extra templates. redirection is not really possible. I can add a note in the templates that tells users to visit those links if their issue is related to one of those plugins?

**Comment by jfbourdon** [comment]
To redirect users, you just need to change the `blank_issues_enabled` line in `config.yml`:

```yml
blank_issues_enabled: false

contact_links:
  - name: Question
    url: https://groups.google.com/g/whiteboxtools
    about: >
      Questions should go to the WhiteboxTools Google Group or other support forums such as https://gis.stackexchange.com/.
      GitHub issues are for bug reports and suggestions for new features.
```

See example for QGIS:
- https://github.com/qgis/QGIS/issues/new/choose
- https://github.com/qgis/QGIS/blob/master/.github/ISSUE_TEMPLATE/config.yml

**Comment by seahawks8** [comment]
> ```yaml
> blank_issues_enabled
> ```

ohh, I learned a new feature. cheers.

**Pull request closed without merging**
