### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -L crate,hsi,ihs,nnumber,numer`

### CODE REVIEW

**Comment by luzpaz** [comment]
8715644  contains changes to source, please review carefully

**Comment by jblindsay** [comment]
This is fantastic and thank you for doing this. I feel terrible seeing all those typos! By the way, how were able to do this spell check operation? What exactly is codespell? Thanks again.

**Comment by giswqs** [comment]
@jblindsay [codespell](https://github.com/codespell-project/codespell) is a Python package for finding and fixing common misspellings in source code and text files. It is a command-line program just like WhiteboxTools. I just started using it last week. You can even integrate it into GitHub Actions to automatically check typos whenever there is push or pull request. Here is how I use it in leafmap.

https://github.com/giswqs/leafmap/blob/master/.github/workflows/docs.yml#L21

**Comment by jblindsay** [comment]
Fantastic, I'll need to start using that in my coding then. It's certainly an improvement in the documentation as well, since much of the docs are generated from the code source files.

**Pull request merged**
